function importCSV(fileToRead)
%IMPORTFILE(FILETOREAD)
%  Imports data from the specified file
%  FILETOREAD:  file to read

%  Auto-generated by MATLAB on 14-Mar-2012 12:32:53

% Import the file
newData = importdata(fileToRead);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData);
for i = 1:length(vars)
    assignin('base', vars{i}, newData.(vars{i}));
end